### ISSUE TITLE
installing plugins in a docker-compose environment

### ISSUE THREAD

**Issue by bmcs-Alex** [bitnami/bitnami-docker-redmine#115] opened 2019-02-19 13:55 UTC
**Description**
trying to install the first plugin (Agile plugin from RedmineUP) in a full functional bitnami/redmine docker environment, which is created with docker-compose.

there is no tutorial for installation of redmine-plugins using docker-compose 

**Steps to reproduce the issue:**
1. copied unarchived plugin into /var/bitnami/redmine/plugins (which is mapped into the image using the docker-compose.yml file, verified with `exec -it  bitnami_redmine_1 bash`

2. redmine is running without the plugin
3. `docker-compose stop`
4. `docker-compose start`
5. mariadb container gets up
6. redmine container stuck (doesn't start)
7. plugin folder clearned
8. `docker-compose start` redmine starts with no issues and without plugins

`docker-compose logs` shows: 
```
redmine_1  | Welcome to the Bitnami redmine container
redmine_1  | INFO  ==> Starting redmine...
redmine_1  | INFO  ==> Starting redmine...
redmine_1  | bundler: failed to load command: passenger (/opt/bitnami/redmine/vendor/bundle/ruby/2.4.0/bin/passenger)
redmine_1  | Bundler::ProductionError: You are trying to install in deployment mode after changing
redmine_1  | your Gemfile. Run `bundle install` elsewhere and add the
redmine_1  | updated Gemfile.lock to version control.
redmine_1  |
redmine_1  | If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze
redmine_1  | by running `bundle install --no-deployment`.
redmine_1  |
redmine_1  | The dependencies in your gemfile changed
redmine_1  |
redmine_1  | You have added to the Gemfile:
redmine_1  | * redmine_crm
redmine_1  |
redmine_1  |   /opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/definition.rb:466:in `ensure_equivalent_gemfile_and_lockfile'
redmine_1  |   /opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:13:in `setup'
redmine_1  |   /opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler.rb:107:in `setup'
redmine_1  |   /opt/bitnami/ruby/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/setup.rb:20:in `<top (required)>'
redmine_1  |   /opt/bitnami/ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
redmine_1  |   /opt/bitnami/ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**results expected:**
Plugin installed

**Version**
- Output of `docker version`:
```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:
```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.809GiB
Name: redmine1
ID: N6DY:NB2W:4RNG:NQCV:7HM3:3BPX:3XF7:EIWH:MMLC:VI7P:YASE:LAGU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):
```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Host: ubuntu lts 18.04 in a HyperV Virtual machine

`more docker-compose.yml`
```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=+*****++
    volumes:
      - '/var/bitnami/mdb:/bitnami'
  redmine:
    image: 'bitnami/redmine:latest'
    environment:
      - REDMINE_DB_PASSWORD=+*****++
      - REDMINE_PASSWORD=******
    ports:
      - '80:3000'
    volumes:
      - '/var/bitnami/redmine:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
```

root@redmine1:/var/bitnami#  `docker exec -it  bitnami_redmine_1 bash`
root@95f531d485d9:/# `echo $BITNAMI_IMAGE_VERSION`
```
4.0.1-debian-9-r21```

**Comment by andresbono** [comment] 2019-02-20 16:11
Hi @bmcs-Alex, which version of Agile plugin are you using?

---
Rel: #23

**Comment by bmcs-Alex** [comment] 2019-02-20 16:59
redmine_agile-1_4_8-light.zip

**Comment by bmcs-Alex** [comment] 2019-02-21 11:33
Hi @andresbono 

here the long answer :) 

I tried to install some other plugins too, but they are not important enough to open an issue. The errors are similar .
I tried to install the issued package (redmine_agile-1_4_8-light) according to the doku here: https://www.redmineup.com/pages/help/agile/installing-redmine-redmine-agile-plugin
but the paths are different in the compose image and the installation fails with an error in regard to some ruby components missing. (its normal I think that there are not all components in the image). Now I deleted all the plugin stuff and take a look over the internet to find some better docu or find support here in the forum.

Thanks in advance

Alex

**Comment by andresbono** [comment] 2019-02-28 11:01
Hi again @bmcs-Alex, sorry for the late response.

We have been checking it and this is how we could install the plugin:

1. Create a new `Dockerfile` in the same directory as the `docker-compose.yml` (name it `Dockerfile-agile`). This new Dockerfile extends the configuration of Redmine. The contents will be:

```Dockerfile
FROM bitnami/redmine:4.0.1-debian-9-r21

RUN install_packages build-essential default-libmysqlclient-dev libpq-dev libmagickwand-dev

WORKDIR /opt/bitnami/redmine

COPY redmine_agile /opt/bitnami/redmine/plugins/redmine_agile
RUN bundle install --no-deployment
RUN bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production
```

2. Modify the `docker-compose.yml` to build the new container by using the new Dockerfile:

```docker-compose
  redmine:
    # image: 'bitnami/redmine:4'
    build:
      context: .
      dockerfile: Dockerfile-agile
```

3. Execute `docker-compose up --build` and you should have the plugin available when Redmine spins up.

Note that this process assumes a first initialization of the container and you will need to remove the persistent volumes. If you prefer to maintain the current data in your volumes, you just need to follow some extra steps:

4. Copy the plugin folder and execute the rake `redmine:plugins` task:
```
docker cp redmine_agile YOUR_REDMINE_CONTAINER:/opt/bitnami/redmine/plugins/redmine_agile
docker exec -it YOUR_REDMINE_CONTAINER bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production
```

5. Restart the container:

```
docker-compose restart redmine
```

**Comment by bmcs-Alex** [comment] 2019-03-04 13:00
I still have some trouble:

after starting step 3 i get an error:

> Step 6/6 : RUN bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production
 ---> Running in faffe2615d83
rake aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
/opt/bitnami/redmine/config/environment.rb:14:in `<top (required)>'
/opt/bitnami/redmine/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in load
/opt/bitnami/ruby/bin/bundle:23:in main
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

and then redmine doesn't start and I can't do any steps in the container.

When I retry  `docker-compose up --build:` again I receive:
>ERROR: Service 'redmine' failed to build: The command '/bin/sh -c bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production' returned a non-zero code: 1

Thanks in advance

Alex

**Comment by bmcs-Alex** [comment] 2019-03-07 10:51
Hi again,

I tried to make a clean run on a fresh vm and got the same Error.

>Step 6/6 : RUN bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production
 ---> Running in f87f404329e8
rake aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
/opt/bitnami/redmine/config/environment.rb:14:in `<top (required)>'
/opt/bitnami/redmine/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `(main)'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
ERROR: Service 'redmine' failed to build: The command '/bin/sh -c bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production' returned a non-zero code: 1
root@intranet:/var/bitnami#

Any Ideas?

Thanks in advance

Alex

**Comment by andresbono** [comment] 2019-03-11 09:00
Hi @bmcs-Alex, can you try by removing the last run in the Dockerfile-agile file? (The one that is failing):

```Dockerfile
FROM bitnami/redmine:4.0.1-debian-9-r21

RUN install_packages build-essential default-libmysqlclient-dev libpq-dev libmagickwand-dev

WORKDIR /opt/bitnami/redmine

COPY redmine_agile /opt/bitnami/redmine/plugins/redmine_agile
RUN bundle install --no-deployment
```

Then, try again.

**Comment by bmcs-Alex** [comment] 2019-03-11 10:01
Hi @andresbono 
SOLVED !!!

thank you very much for your support.

maybe i'll have to come back to this thread in case of an update. But for now it is working.

**Comment by andresbono** [comment] 2019-03-14 13:41
That's great @bmcs-Alex!! :tada:

We are closing the issue.

**Closed by andresbono** 2019-03-14 13:41 UTC

**Comment by thanhtai9606** [comment] 2021-02-17 02:34
I cannot install plugin agile light on bitnami/redmine:4.1.1-debian-10-r209. I tried build it, but failed, 
`Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze
by running `bundle config unset deployment`.

The dependencies in your gemfile changed

You have added to the Gemfile:
* redmine_crm
The command '/bin/sh -c bundle install --no-deployment' returned a non-zero code: 16
ERROR: Service 'redmine' failed to build`

**Comment by andresbono** [comment] 2021-02-17 15:17
Hi @thanhtai9606, are you following these steps? https://github.com/bitnami/bitnami-docker-redmine/issues/115#issuecomment-468231005

**Comment by KoertLichtendonk** [comment] 2021-02-19 08:16
> 
> 
> I cannot install plugin agile light on bitnami/redmine:4.1.1-debian-10-r209. I tried build it, but failed,
> 
> > `Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine. You are trying to install in deployment mode after changing your Gemfile. Run `bundle install` elsewhere and add the
> > updated Gemfile.lock to version control.
> > If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze
> > by running `bundle config unset deployment`.
> > The dependencies in your gemfile changed
> > You have added to the Gemfile:
> > 
> > * redmine_crm
> >   The command '/bin/sh -c bundle install --no-deployment' returned a non-zero code: 16
> >   ERROR: Service 'redmine' failed to build`

I have the exact same problem. @andresbono Yes, apart from the different Redmine version that @thanhtai9606 has too, which also seems the cause of the problem because with the version you use it works fine.

**Comment by andresbono** [comment] 2021-02-21 18:53
Hi @KoertLichtendonk, @thanhtai9606, you can try to execute the bundle command that is failing with the `1001` user, the uid of `redmine`. To do so, modify the command to:

```
RUN gosu 1001 bundle install --no-deployment
```

**Comment by thanhtai9606** [comment] 2021-02-23 01:06
> > I cannot install plugin agile light on bitnami/redmine:4.1.1-debian-10-r209. I tried build it, but failed,
> > > `Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine. You are trying to install in deployment mode after changing your Gemfile. Run `bundle install`elsewhere and add the updated Gemfile.lock to version control. If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze by running`bundle config unset deployment`.
> > > The dependencies in your gemfile changed
> > > You have added to the Gemfile:
> > > 
> > > * redmine_crm
> > >   The command '/bin/sh -c bundle install --no-deployment' returned a non-zero code: 16
> > >   ERROR: Service 'redmine' failed to build`
> 
> I have the exact same problem. @andresbono Yes, apart from the different Redmine version that @thanhtai9606 has too, which also seems the cause of the problem because with the version you use it works fine. Unfortunately I need the latest Redmine version. Any ideas how to fix this?

I was fixed it!!
This is my source. You can follow it!!
https://github.com/thanhtai9606/redmine-owner.git

**Comment by rafariossaa** [comment] 2021-02-23 16:48
Hi,
  @thanhtai9606, I am happy you were able to solve it. 
  Thank you very much for sharing.

**Comment by nomopo45** [comment] 2022-03-23 10:12
Hello I have been trying to create an image with the plugins included, to use it in my AWS EKS Cluster, but each time i do any modification on the base image my pod won't start and the error will be : 

`Error: open /opt/bitnami/redmine/config/database.yml: no such file or directory`

but the file is present on the image i'm creating so i don't understand.

my Dockerfile : 
`FROM bitnami/redmine:4.2.4-debian-10-r0

RUN install_packages build-essential default-libmysqlclient-dev libpq-dev libmagickwand-dev

WORKDIR /opt/bitnami/redmine

COPY additionals /opt/bitnami/redmine/plugins/additionals
COPY redmine_saml /opt/bitnami/redmine/plugins/redmine_saml
COPY redmine_saml/sample-saml-initializers.rb /opt/bitnami/redmine/config/initializers/saml.rb

RUN cd /opt/bitnami/redmine && bundle config set --local deployment 'false'
RUN cd /opt/bitnami/redmine && bundle install

RUN bundle exec rake redmine:plugins:migrate RAILS_ENV=production`

Any idea to fix this ?

**Comment by rafariossaa** [comment] 2022-03-23 10:29
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-redmine#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by dot-mike** [comment] 2022-03-31 12:35
> Hello I have been trying to create an image with the plugins included, to use it in my AWS EKS Cluster, but each time i do any modification on the base image my pod won't start and the error will be :
> 
> `Error: open /opt/bitnami/redmine/config/database.yml: no such file or directory`
> 
> but the file is present on the image i'm creating so i don't understand.

In your Dockerfile, you are trying to migrate Redmine database before it exists:
 `RUN bundle exec rake redmine:plugins:migrate RAILS_ENV=production`

Remove the line and allow Bitnami to take care of bootstraping Redmine including migrating the database.

**Comment by nomopo45** [comment] 2022-03-31 12:42
> @nomopo45
> 
> > Hello I have been trying to create an image with the plugins included, to use it in my AWS EKS Cluster, but each time i do any modification on the base image my pod won't start and the error will be :
> > `Error: open /opt/bitnami/redmine/config/database.yml: no such file or directory`
> > but the file is present on the image i'm creating so i don't understand.
> 
> In your Dockerfile, you are trying to migrate Redmine database before it exists: `RUN bundle exec rake redmine:plugins:migrate RAILS_ENV=production`
> 
> Remove the line and allow Bitnami to take care of bootstraping Redmine including migrating the database.

In the end every modification even the slightest like an "RUN echo lol" in the dockerfile ended in an error, so i used the official redmine image (not the bitnami one) and i manage to make it work.

thank you
