### ISSUE TITLE
Upgrade fails with " NameError: uninitialized constant ActionDispatch::ParamsParser"

### ISSUE THREAD

**Issue by rosch100** [bitnami/bitnami-docker-redmine#109] opened 2019-01-04 10:16 UTC
**Description**

On a previously working docker installation of bitnami-redmine, the container fails now.

**Describe the results you received:**

Log output:

```
Welcome to the Bitnami redmine container

Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine

Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues


nami    INFO  Initializing redmine

redmine INFO  Redmine has been already initialized, restoring...

mysql-c INFO  Trying to connect to MySQL server

mysql-c INFO  Found MySQL server listening at mariadb:3306

mysql-c INFO  MySQL server listening and working at mariadb:3306

redmine INFO  Generating new secret...

Error executing 'postInstallation': rake aborted!

NameError: uninitialized constant ActionDispatch::ParamsParser

/opt/bitnami/redmine/config/application.rb:55:in `<class:Application>'

/opt/bitnami/redmine/config/application.rb:8:in `<module:RedmineApp>'

/opt/bitnami/redmine/config/application.rb:7:in `<top (required)>'

/opt/bitnami/redmine/Rakefile:5:in `require'

/opt/bitnami/redmine/Rakefile:5:in `<top (required)>'

/opt/bitnami/redmine/vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'

/opt/bitnami/ruby/bin/bundle:23:in `load'

/opt/bitnami/ruby/bin/bundle:23:in `<main>'

(See full trace by running task with --trace)
```

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 14
 Running: 12
 Paused: 0
 Stopped: 2
Images: 43
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-43-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.56GiB
Name: docker
ID: DCJT:4IXN:HFKB:4CQ3:6JTW:5CVA:AOQI:GEP6:34AH:6Q7K:N2PU:PAS3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by rosch100** [comment] 2019-01-07 14:49
I am on bitnami/redmine:latest
The target version to upgrade to is the most current version. The previous version is the one, which you had before in bitnami/redmine:latest.

**Comment by tompizmor** [comment] 2019-01-08 15:39
So I guess you were updating from the latest version of the 3 branches (3.4.7) to the latest version of the 4 branches (4.0.0).

I tried with those versions and I was able to reproduce the issue. I guess the standard procedure of migrating the database does not work well between major version. 

We will further investigate the issue. However, as it is an upgrade to a new major version it is possible that some manual steps are required.

**Comment by rosch100** [comment] 2019-01-08 15:47
Yes, that should be the case (3.4.7 to4.0.0). Manual steps should not be an issue. Please let me know, how to proceed when you find a workaround.
Meanwhile, would it be possible to go back to 3.4.7.?

**Comment by tompizmor** [comment] 2019-01-08 16:18
> Meanwhile, would it be possible to go back to 3.4.7.?

Yes.  
- Run `docker-compose down` to delete the containers. 
- Then, edit the docker-compose file and change the redmine image to use the 3.4.7 tag (` image: 'bitnami/redmine:3.4.7'`). 
- Finally, run `docker-compose up` again

**Comment by tompizmor** [comment] 2019-01-09 08:31
Glad to hear that! We will update this issue once we have more information about the upgrade from 3 to 4.

**Comment by rosch100** [comment] 2019-03-14 08:11
Any news on the upgrade issue?

**Comment by tompizmor** [comment] 2019-03-15 12:00
Hi @rosch100,

I took another look and I have identified the issue. The problem is that the file `/opt/bitnami/redmine/config/application.rb` was being persisted and it should be updated for redmine 4.

I am working on a release of Redmine 4 that does not restore this file so the upgrade should work well after that.

**Comment by rosch100** [comment] 2019-03-15 12:17
Hi Tomas,
thanks a lot!

**Comment by tompizmor** [comment] 2019-03-18 16:39
@rosch100 We have finished the release of the redmine container. Can you try the upgrade now?

**Comment by rosch100** [comment] 2019-03-18 16:48
Hi Thomas,
the upgrade and db migration went smoothly without any errors. I’m now on redmine 4.02

Thanks for your support!

Roland

**Comment by tompizmor** [comment] 2019-03-18 16:55
I am glad it worked! 
I am closing this issue. Please open a new one if you find any other issue.

**Closed by tompizmor** 2019-03-18 16:55 UTC
