### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by nguyenhaiphan** [bitnami/bitnami-docker-redmine#84] opened 2017-03-20 10:10 UTC
Hi, after initialize the docker container with default configuration, I try to add SMTP configuration. I stop the container and "up" it again but the Email settings keep telling me:

Email delivery is not configured, and notifications are disabled. 
Configure your SMTP server in config/configuration.yml and restart the application to enable them.

How can I make the container understand my updated config in yml?

Regards,

**Comment by silviofdez** [comment] 2017-03-20 13:32
Hi, 

have you tried to modify the SMTP setting via modifying the docker-compose file, passing arguments to the docker itself or setting the ENV vars previously? You have to pass these options each time you start the container.

**Comment by nguyenhaiphan** [comment] 2017-03-21 01:56
Hi, I modified the docker-compose.yml follow the readme example, then stop the container and Up it again. But without any success.

redmine:
...
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=[my email]
      - SMTP_PASSWORD=[my password]

**Comment by silviofdez** [comment] 2017-03-22 16:17
Hi,

I cannot reproduce your issue. It works fine even after restart the container. Please check this instruction in order to allow _less_ _secure_ _apps_ to connect to your Gmail account. https://docs.bitnami.com/google/apps/wordpress/#troubleshooting-gmail-smtp-issues

We are going to close the issue.

**Closed by silviofdez** 2017-03-22 16:17 UTC

**Comment by nguyenhaiphan** [comment] 2017-09-06 14:39
I figured that I should docker-compose build (--no-cache) to rebuild the edited environment. Thank you for your support.

**Comment by drew-kun** [comment] 2021-06-24 14:54
@silviofdez @nguyenhaiphan, I am seeing the same issue:
```yaml
version: "3.5"
services:
  redmine:
    restart: always
    image: bitnami/redmine:4.2.1
    container_name: snec-tko_redmine
    volumes:
    - redmine-data:/bitnami
    - /usr/bin/ssh:/usr/bin/ssh
    - /srv/docker-compose-cicd/redmine/config/ssh:/root/.ssh
    ports:
    - 10.176.40.21:8001:3000
    environment:
    - "REDMINE_USERNAME=redmine-admin"
    - "REDMINE_PASSWORD=P@$$w0rd"
    - "REDMINE_DB_NAME=bitnami-redmine"
    - "REDMINE_DB_USERNAME=redmine"
    - "REDMINE_DB_PASSWORD=P@$$w0rd"
    - "SMTP_HOST=smtp.office365.com"
    - "SMTP_PORT=587"
    - "SMTP_USER=redmine@my-domain"
    - "SMTP_PASSWORD=SMTPP@$$w0rd"
    - "SMTP_TLS=true"
    - "SMTP_DOMAIN=my-domain"
    - "SMTP_AUTHENTICATION=login"
```
But in Administration > Settings I see this:
<img width="1272" alt="Screen Shot 2021-06-24 at 5 45 01 PM" src="https://user-images.githubusercontent.com/10493450/123283366-01ba9780-d514-11eb-8e12-b4e56a8876e2.png">

So after `docker-compose down`, and `docker-compose up -d` the ENV Variables are set correctly within container:
```bash
root@9b57982f30b9:/bitnami/redmine/conf# echo $SMTP_USER
redmine@my-domain
root@9b57982f30b9:/bitnami/redmine/conf# echo $SMTP_PASSWORD
SMTPP@$$w0rd"
....
```

But my `/bitnami/redmine/conf/configuration.yml` still has all SMTP settings commented out:

```yaml
# default configuration options for all environments
default:
  # Outgoing emails configuration
  # See the examples below and the Rails guide for more configuration options:
  # http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
  email_delivery:

  # ==== Simple SMTP server at localhost
  #
  #  email_delivery:
  #    delivery_method: :smtp
  #    smtp_settings:
  #      address: "localhost"
  #      port: 25
  #
  # ==== SMTP server at example.com using LOGIN authentication and checking HELO for foo.com
  #
  #  email_delivery:
  #    delivery_method: :smtp
  #    smtp_settings:
  #      address: "example.com"
  #      port: 25
  #      authentication: :login
  #      domain: 'foo.com'
  #      user_name: 'myaccount'
  #      password: 'password'
  #
  # ==== SMTP server at example.com using PLAIN authentication
  #
  #  email_delivery:
  #    delivery_method: :smtp
  #    smtp_settings:
  #      address: "example.com"
  #      port: 25
  #      authentication: :plain
  #      domain: 'example.com'
  #      user_name: 'myaccount'
  #      password: 'password'
  #
  # ==== SMTP server at using TLS (GMail)
  # This might require some additional configuration. See the guides at:
  # http://www.redmine.org/projects/redmine/wiki/EmailConfiguration
  #
  #  email_delivery:
  #    delivery_method: :smtp
  #    smtp_settings:
  #      enable_starttls_auto: true
  #      address: "smtp.gmail.com"
  #      port: 587
  #      domain: "smtp.gmail.com" # 'your.domain.com' for GoogleApps
  #      authentication: :plain
  #      user_name: "your_email@gmail.com"
  #      password: "your_password"
  #
  # ==== Sendmail command
  #
  #  email_delivery:
  #    delivery_method: :sendmail
```
Please, let me know what may be wrong?

**Comment by migruiz4** [comment] 2021-06-25 06:29
Hi @drew-kun,

I'm sorry for the inconvenience, but changes to SMTP settings won't apply after the application has been initialized for the first time.

You could change the configuration manually and changes will be persisted, or if you don't have any persistent data yet you could delete the volume and restart the container.

**Comment by drew-kun** [comment] 2021-06-25 08:40
Oh I see... That's unfortunate, because our team already has persistent data. Anyway, thank you for confirming this, as I thought that I was doing something wrong. I will mount the configuration.yml then.
